import { z } from 'zod'

export const noteInputSchema = z.object({
  title: z.string().min(1).max(200),
  content: z.string().default(''),
  type: z.enum([
    'product-idea',
    'ui-idea',
    'feature-idea',
    'campaign-idea',
    'copy-idea',
    'offer-idea',
    'client-feedback',
    'market-insight',
    'sales-learning',
    'strategic-decision',
    'useful-prompt',
    'visual-reference',
    'bug-improvement',
    'onboarding-idea',
    'pricing-idea',
    'brandkit-idea',
    'other',
  ]),
  tagIds: z.array(z.string()).default([]),
  relatedTo: z.enum([
    'lead',
    'client',
    'product',
    'campaign',
    'ui',
    'sales',
    'social',
    'meta-ads',
    'general',
  ]),
  priority: z.enum(['low', 'medium', 'high']),
  status: z.enum(['draft', 'review', 'approved', 'in-progress', 'archived']),
  pinned: z.boolean().default(false),
  favorited: z.boolean().default(false),
  expectedImpact: z.enum(['low', 'medium', 'high']).optional(),
  estimatedEffort: z.enum(['low', 'medium', 'high']).optional(),
})
